"""Tests for DayRepReport parser and REG normalization."""

import pytest
import pandas as pd
import tempfile
import os

from src.parser.dayrep_parser import normalize_reg, find_header_row, parse_dayrep_report


class TestNormalizeReg:
    def test_standard_format(self):
        assert normalize_reg("VN-A500") == "VN-A500"

    def test_missing_hyphen(self):
        assert normalize_reg("VNA500") == "VN-A500"

    def test_leading_space(self):
        assert normalize_reg(" VN-A500") == "VN-A500"

    def test_trailing_space(self):
        assert normalize_reg("VN-A500 ") == "VN-A500"

    def test_lowercase(self):
        assert normalize_reg("vn-a500") == "VN-A500"

    def test_none(self):
        assert normalize_reg(None) is None

    def test_empty_string(self):
        assert normalize_reg("") is None

    def test_nan(self):
        assert normalize_reg(float("nan")) is None


class TestFindHeaderRow:
    def test_standard_header(self):
        data = [
            ["Report Title", "", "", "", "", "", "", ""],
            ["Generated: 2026-04-24", "", "", "", "", "", "", ""],
            ["DATE", "FLT", "REG", "AC", "DEP", "ARR", "STD", "STA"],
            ["24/04/2026", "1504", "VN-A500", "A321", "DAD", "HAN", "12:40", "14:00"],
        ]
        df = pd.DataFrame(data)
        assert find_header_row(df) == 2

    def test_variant_header_names(self):
        data = [
            ["Title", "", "", "", "", "", "", ""],
            ["FLIGHT DATE", "FLT NO", "REGISTRATION", "AIRCRAFT TYPE", "FROM", "TO", "SCHED DEP", "SCHED ARR"],
            ["24/04/2026", "1504", "VN-A500", "A321", "DAD", "HAN", "12:40", "14:00"],
        ]
        df = pd.DataFrame(data)
        assert find_header_row(df) == 1

    def test_no_header_raises(self):
        data = [
            ["foo", "bar", "baz", "qux", "quux", "corge", "grault", "garply"],
            ["a", "b", "c", "d", "e", "f", "g", "h"],
        ]
        df = pd.DataFrame(data)
        with pytest.raises(ValueError, match="HEADER_NOT_FOUND"):
            find_header_row(df)


class TestParseDayrepReport:
    def _create_test_excel(self, rows: list[list]) -> str:
        """Create a temporary Excel file from row data."""
        df = pd.DataFrame(rows)
        tmp = tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False)
        df.to_excel(tmp.name, index=False, header=False)
        return tmp.name

    def test_basic_parsing(self):
        rows = [
            ["Report Title", "", "", "", "", "", "", ""],
            ["DATE", "FLT", "REG", "AC", "DEP", "ARR", "STD", "STA"],
            ["24/04/2026", "1504", "VN-A500", "A321", "DAD", "HAN", "12:40", "14:00"],
            ["24/04/2026", "1505", "VN-A500", "A321", "HAN", "DAD", "14:35", "15:55"],
        ]
        path = self._create_test_excel(rows)
        try:
            df, warnings = parse_dayrep_report(path)
            assert len(df) == 2
            assert df.iloc[0]["flight_no"] == "1504"
            assert df.iloc[0]["origin"] == "DAD"
            assert df.iloc[0]["destination"] == "HAN"
        finally:
            os.unlink(path)

    def test_footer_rows_skipped(self):
        rows = [
            ["DATE", "FLT", "REG", "AC", "DEP", "ARR", "STD", "STA"],
            ["24/04/2026", "1504", "VN-A500", "A321", "DAD", "HAN", "12:40", "14:00"],
            ["Total: 1 flight", "", "", "", "", "", "", ""],
            ["Generated by AIMS v8.2", "", "", "", "", "", "", ""],
        ]
        path = self._create_test_excel(rows)
        try:
            df, warnings = parse_dayrep_report(path)
            assert len(df) == 1
            footer_warnings = [w for w in warnings if "FOOTER_ROW_SKIPPED" in w]
            assert len(footer_warnings) >= 1
        finally:
            os.unlink(path)

    def test_reg_normalization_in_parser(self):
        rows = [
            ["DATE", "FLT", "REG", "AC", "DEP", "ARR", "STD", "STA"],
            ["24/04/2026", "1504", "VNA500", "A321", "DAD", "HAN", "12:40", "14:00"],
            ["24/04/2026", "1505", " vn-a500 ", "A321", "HAN", "DAD", "14:35", "15:55"],
        ]
        path = self._create_test_excel(rows)
        try:
            df, warnings = parse_dayrep_report(path)
            assert df.iloc[0]["aircraft_reg"] == "VN-A500"
            assert df.iloc[1]["aircraft_reg"] == "VN-A500"
        finally:
            os.unlink(path)

    def test_variant_column_names(self):
        rows = [
            ["FLIGHT DATE", "FLT NO", "TAIL", "TYPE", "FROM", "TO", "SCHED DEP", "SCHED ARR"],
            ["24/04/2026", "1504", "VN-A500", "A321", "DAD", "HAN", "12:40", "14:00"],
        ]
        path = self._create_test_excel(rows)
        try:
            df, warnings = parse_dayrep_report(path)
            assert len(df) == 1
            assert "flight_no" in df.columns
            assert "origin" in df.columns
            assert "destination" in df.columns
        finally:
            os.unlink(path)
